const boxTag = document.getElementById('box')
boxTag.style.height = '200px'
boxTag.style.width = '300px'
boxTag.style.backgroundColor = 'yellow'
boxTag.style.margin = '20px'
boxTag.style.padding = '10px'
boxTag.style.fontSize = '18px'
boxTag.style.fontWeight = 'bold'
boxTag.style.color = 'blue'
